### ISSUE TITLE
feat: "Select All" button for transfer list

### ISSUE THREAD

**Issue by moskale-mukola** [ckalgos/fut-trade-enhancer#104]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

"Select All" button for transfer list
https://i.imgur.com/INLw2FW.png

### Describe the Use Case

1. I sent unnecessary cards from the cloud for sale
2. I want to sell them at the price from Futbin.
3. In Transfer list I have cards that I do not want to sell

### Describe Preferred Solution

1. After adding unnecessary cards to Transfer List, I click the "Select All" button
2. Remove the checkbox from the needed cards
3. Click "List FUTBIN"

Expected result: selected cards were put up for sale

### Describe Alternatives

-

### Additional Information

We have added the possibility of mass actions for Transfer List. Additionally, button "Select All" would be realy useful.
Now, if there are 70 cards in the Transfer List, and if I want to sell 65 (the other 5 are duplicates, I can't send them to the club), I need to select the checkbox 65 times. Button "Select All" will reduce this to 5 clicks

P.S. I thank you very much for everything you do for the community

**Comment by ckalgos** [comment]
In the latest version all cards will be selected by default, you can uncheck cards

**Comment by moskale-mukola** [comment]
@ckalgos yes, many thanks
