### ISSUE TITLE
feat: Find lowest price on market

### ISSUE THREAD

**Issue by captain-cronch** [ckalgos/fut-trade-enhancer#106]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Finds actual current market price for given card. FUTBIN/FUTWIZ data is often outdated.

### Describe the Use Case

When finding proper list prices for cards (often bronzes when doing BPM), this feature would allow for pricing that would ensure quick, but optimal sales. Many bronze cards have outdated prices on FUTBIN/FUTWIZ and this would streamline the listing process.

### Describe Preferred Solution

There are two different methods that I see that would accomplish this goal:
1) Using the "Compare Price" to scan current listings and determining what the 3 lowest sale prices are within 1 hour.
2) Using current FUTBIN/FUTWIZ price as a base search and incrementally searching higher or lower until these 3 sale prices are found.

### Describe Alternatives

Manually searching is currently the only alternative.

### Additional Information

This feature would also allow for quick price finding when looking to purchase cards.

**Comment by ckalgos** [comment]
Added in the latest version
