### ISSUE TITLE
Highlight specific cards

### ISSUE THREAD

**Issue by markoo7** [ckalgos/fut-trade-enhancer#108]
For example while we are searching for Manager Leagues in the Consumables tab, we can see that normally we would have as result everything as a whole, without the possibility to filter after the league.

I was thinking that maybe, exactly as the Enhancer works with the color highlight when it sees something lower in price, we could have an option to select certain leagues to be highlighted in colors while searching for Manager Leagues.

**Comment by ckalgos** [comment]
Added in the new release
