### ISSUE TITLE
Items expiring time is mixed up

### ISSUE THREAD

**Issue by markoo7** [ckalgos/fut-trade-enhancer#109]
Preconditions:
1. Version 1.4.3 used (latest at this moment in time).
2. Activate "Increase Search Result" from the Enhancer tab.

Actions:
1. Perform searches which will return over 51 items.
2. Notice the order of the returned items.

Expected:
Items must be in the timer countdown order, instead they are mixed up: sometimes at the beginning there are  items with 59 minutes left, then others with 2 minutes left, then with 30 minutes and so on, they are not consecutive in regards with the selling time left as they should.

Recovery:
Disable the Enhancer option and search again.

**Comment by chenei** [comment]
@markoo7 they are sorting the items based on the lowest bin first.

**Comment by ckalgos** [comment]
Fixed in the latest version

**Comment by markoo7** [comment]
@ckalgos In the latest version meaning the one which is yet to come next, right?
Thanks for checking!
