### ISSUE TITLE
question: does the new 51 players feature is not risk us with a ban?

### ISSUE THREAD

**Issue by chenei** [ckalgos/fut-trade-enhancer#110]
Hey,

I wonder if this feature is not too risky of a permanent ban. 

All other features on the extension are simply javascript/html/css manipulations.

On this feature, you are requesting from the EA server 50 players, you are actually telling them you are using an extension because this request is not available on any other official client apps.

**Comment by ckalgos** [comment]
Hey,

Even I would advice not to turn it on for the same reason you suggested. But so many people were asking for it, hence we added it.

Having said that for the past week fully I was having 50 cards search, havent got banned yet. So if you are going to use it for few searches in between I guess you should be ok.
