### ISSUE TITLE
feat: Auto Open Pack addition

### ISSUE THREAD

**Issue by markoo7** [ckalgos/fut-trade-enhancer#112]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Below description and request applies for Bronze and Silver Packs only.

It is known that inside such a pack there are also other important items apart from the players.
Not having additional options to deal with items other than players specifically is quite a shame. :(

At least please consider adding an option for the manager cards that could pop.

### Describe the Use Case

Example of use case with this new enhancement added:

1. Go to Classic Packs
2. Click Open pack automatically for Premium Bronze Pack
3. Select desired options for auto opening

### Describe Preferred Solution

In the Auto Open Packs window split "Non players" section into multiple sections, for each type of item which could appear (or at least into Managers and "the rest").

Items which are being bulk handled right now:
- common managers
- rare managers
- common contracts
- rare contracts
- common kits
- rare kits
- common badges
- rare badges
- common balls
- common stadium flares

**Comment by ckalgos** [comment]
Added in the new release
