### ISSUE TITLE
feat: Expanded options in auto-pack openings

### ISSUE THREAD

**Issue by captain-cronch** [ckalgos/fut-trade-enhancer#115]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Provides more sorting options for auto-pack opener.

### Describe the Use Case

While bronze rare player prices are high following the release of Icon SBCs, it would be advantageous to have the ability to automatically list bronze rare players when auto-opening bronze packs. Some common bronze players from popular leagues and nations also will regularly have good value to be sold and could be filtered by FUTBIN price.

It would also be beneficial to provide different options for non-player items by category.
-Contracts
-Staff
-Club Items

### Describe Preferred Solution

The addition of fields to differentiate common and rare players, duplicate players, and club items.
The addition of ability to list a certain category for X or FUTBIN (or maybe even the greater of the two)
The addition of ability to compare price for selected categories before determining where to sort to.

### Describe Alternatives

Alternative solution:
Do it all manually after it's been sent to club. Duplicates go to transfer list before manually comparing price to either quick sell or list.

### Additional Information

Some bronze club items can sell for 5k coins. Others won't sell at all. The limited options of the auto-opener in its current form prevent it from being as profitable as it could be while prices are high for certain categories and players.

An additional feature that would be nice would be if the opener could reference saved filters and sort items based on if they fit a particular filter. For example, if there were a current SBC calling for players from Eng. League One, any players that fit that filter could be sent to transfer list or listed for FUTBIN/current minimum BIN

**Comment by captain-cronch** [comment]
I attempted to edit .\app\utils\openPacksUtil.js and relevant files that were imported to create the changes I was hoping to see, but unfortunately changing the extension isn't as simple as it was back on FIFA 21 when I had previously made minor changes. I don't know JS well enough to write it, but can follow along and make changes as necessary to accomplish my means. I'm also not familiar with compiling directories to test through tampermonkey, otherwise I would have tested the changes made.

If anyone reading this is familiar with this issue and can help walk me through it, I'd love to attempt to make some of the changes I am hoping to be implemented and creating a branch to further the script.

Thanks.

**Comment by ckalgos** [comment]
Added in the new release
