### ISSUE TITLE
relist futbin freeze

### ISSUE THREAD

**Issue by Waller1337** [ckalgos/fut-trade-enhancer#116]
After the new update when select relist futbin after a few moments the browser (opera, chrome) gets a freeze.

**Comment by ckalgos** [comment]
how many player you had in the transferlist? and what's your chrome version?

**Comment by Waller1337** [comment]
approximately 30-50 players , Chrome version is 107

**Comment by Waller1337** [comment]
on version 1.4.3 this error does not occur in the same browsers tested

**Comment by ckalgos** [comment]
Fixed in latest release
