### ISSUE TITLE
bug: web app suspend when add players to SBC

### ISSUE THREAD

**Issue by Kokoraky** [ckalgos/fut-trade-enhancer#117]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.5.2

### Platform

Webapp

### Current Behavior

web app crashes when i add up to 3, 4 players to SBC. Problem encountered when i update to version 1.5.2
![Screenshot 2022-11-05 091052](https://user-images.githubusercontent.com/82558576/200096548-2f213443-4ac8-4be6-bb0a-9e0860296d5f.png)

### Expected Behavior

fix it or how can i go back to the previous version?

### Steps to Reproduce

.

**Comment by ckalgos** [comment]
Fixed in latest release
