### ISSUE TITLE
Building App

### ISSUE THREAD

**Issue by SergiuAM** [ckalgos/fut-trade-enhancer#129]
Hello. I am a FIFA player and I'm working as a full-stack developer also. I tried to do some changes on the project, just for testing now, but I don't know how to build the app properly. It seems like it doesn't import the external jQuery and Font-Awesome in Tempermonkey if I'm adding the min that the builder is creating as it is now. Can you guys help me with this? @marcelotk15 @ckalgos @ebugday81

**Comment by chlebta** [comment]
Am intersted too, I tried `yarn build:dev` then I reinstalled the `fut-trade-enhancer.user.js` but doesn't work I get 

`index.js:19 Uncaught (in promise) TypeError: _external_amplify__WEBPACK_IMPORTED_MODULE_6__.default.configure is not a function`

**Comment by ckalgos** [comment]
Fixed in the new release
