### ISSUE TITLE
highlights players who are a certain percentage under their 7 day average, like so

### ISSUE THREAD

**Issue by noob8989** [ckalgos/fut-trade-enhancer#40]
For example, say you set your percentage to 10. Any player that is 10%+ less than their 7 day average will be visually highlighted green

Is that possible to build into the autobayer?
Here Exapmle

![image](https://user-images.githubusercontent.com/76663272/139668276-03266dcf-bd7d-4bb0-9d50-8c9ebba68f70.png)

THX

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
