### ISSUE TITLE
feat: ability to use filters saved from "Autobuyer" tab in "Transfers" tab 

### ISSUE THREAD

**Issue by ahmaarek** [ckalgos/fut-trade-enhancer#57]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

-Ability to load and/or save filters just like in the autobuyer tab, but in the transfers tab. 

### Describe the Use Case

This will help track prices for consumables, silvers, bronzes, etc (cards that are not frequently updated on futbin).

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
