### ISSUE TITLE
bug: SBC Autofill still not working 

### ISSUE THREAD

**Issue by dpearson2699** [ckalgos/fut-trade-enhancer#60]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.2.0

### Platform

Webapp

### Current Behavior

After entering in the Futbin SBC ID it fills the squad with the correct players, but still in the incorrect positions.

### Expected Behavior

To fill the squad with the players in the correct position listed in the community SBC solution

### Steps to Reproduce

The SBC Super-Sub using the Futbin id of: 100144622 fills out the SBC in the FUT web app like this:
![image](https://user-images.githubusercontent.com/32114370/147836244-61d23a4d-3302-411e-9cdf-bb8384bece57.png)

When it should fill out the players like this:
![image](https://user-images.githubusercontent.com/32114370/147836259-c9395832-82ea-4666-b896-027db97c148e.png)

### Additional Information

My previous bug report was closed because it was claimed to have been fixed in this release but unfortunately that is not the case.

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
