### ISSUE TITLE
feat: sell only

### ISSUE THREAD

**Issue by erfann20** [ckalgos/fut-trade-enhancer#64]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

It would be great if you could only SELL cards and not to buy them and list them at the same time. For a set price other than FUTBIN price.

### Describe the Use Case

 some times i mass buy a card to hold for a while and sell later when it gets more expensive and listing for example 50 identical cards one by one with the same exact price is a pain.

### Describe Preferred Solution

It would be nice to select a player or a consumable and set the bot to sell for example 20 of it from your inventory/club for a set price

### Additional Information

Great job by the way
I really appreciate you for creating such useful tool and sharing it for free
Thank you in advance 💗

**Comment by ckalgos** [comment]
Added in the latest release
