### ISSUE TITLE
Double click to bid 

### ISSUE THREAD

**Issue by Kacik** [ckalgos/fut-trade-enhancer#67]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Would be perfect to have option of auto bid after double click left mouse button.

### Describe the Use Case

Would be perfect to have option of auto bid after double click left mouse button.

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
