### ISSUE TITLE
[Re-list FutBIN] list processing breaks

### ISSUE THREAD

**Issue by faegan** [ckalgos/fut-trade-enhancer#71]
When processing a list of players on the [Unsold items] list or [Available items] list and one of the players returns a 0 (zero) or "--" (none) value from FutBIN, the function will get stuck in a loop. 

To reproduce: 
Step 1: put 5 players with a "normal" FUTBin price on [Available Items] list by using the option [Send to Transfer list] 
Step 2: put one player with 0 or "--" FUTBin price on [Available Items] list by using the option [Send to Transfer list]
Step 3 : put 3 players with a "normal" FUTBin price on [Available Items] list by using the option [Send to Transfer list]
Step 4: Go to transfer list and press the [Re-list Futbin] option

Expected result: processing all items, but leaving the "malformed"/"mal-priced" item

Actual result: listing of 3 players and getting stuck in a loop trying to list the item for 0.

**Comment by ckalgos** [comment]
Should be fixed now
