### ISSUE TITLE
feat: instead of scraping only the last Futbin price, scrape lowest 3 BIN and how long ago was the price updated

### ISSUE THREAD

**Issue by Ibra-x** [ckalgos/fut-trade-enhancer#73]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

instead of scraping only the last Futbin price, scrape lowest 3 BIN and how long ago was the price updated

here is an image example of it: [https://i.gyazo.com/5ed7db79420e09d2f64dbfe0571f68ed.png](https://i.gyazo.com/5ed7db79420e09d2f64dbfe0571f68ed.png)

### Describe the Use Case

sometimes the lowest price is very different from the next 2 prices, also sometimes the price was not updated for a long time.
this feature would solve both problems.

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
