### ISSUE TITLE
feat:  BRONZE / SILVER UPGRADE SBCs AUTOFILL FROM CLUB ITEMS

### ISSUE THREAD

**Issue by victormai121** [ckalgos/fut-trade-enhancer#74]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Hi Team,

It would be nice if FOUNDATION UPGRADES (BRONZE/SILVER UPGRADES) SBCs can have AUTOFILL function from Club Items as well.
It also allows the uses to choose the quality / rarity / league (to pick and NOT to pick) and autofill all of the 11 spots in each upgrade SBC.

Lovely to hear from you soon.

Regards,
V

### Describe the Use Case

BRONZE / SILVER UPGRADE SBCs AUTOFILL FROM CLUB ITEMS

**Comment by ckalgos** [comment]
Closing the issue for FIFA 23
