### ISSUE TITLE
feat: Futbin consumables price

### ISSUE THREAD

**Issue by MMZaini** [ckalgos/fut-trade-enhancer#75]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

When "Listing for futbin price" only players are sold however futbin does have a [consumables price section ](https://www.futbin.com/consumables) for [postion changers](https://www.futbin.com/consumables/Position%20Change) and [chemistry styles ](https://www.futbin.com/consumables/Chemistry%20Styles)

### Describe the Use Case

This would help out tremendously as it would speed up the selling of items with in the transfer list

### Describe Preferred Solution

Do the same thing you're doing with the players but adjust it for consumables!

**Comment by ckalgos** [comment]
This is now available in the latest script
