### ISSUE TITLE
Feature Request: Futbin Player Page on Search Results

### ISSUE THREAD

**Issue by Feigenstaub** [ckalgos/fut-trade-enhancer#80]
I miss the button on transfermarket search results on every player where it opens up quickly the futbin playerpage. It exists in my club players but not (anymore?) in transfermarket and in fifa 22 I used it a lot while trading and looking for some deals and to confirm quickly the prices on futbin.

would be nice to have it back there.

thanks and great work!

**Comment by ckalgos** [comment]
Added in Latest Release
