### ISSUE TITLE
feat: Bot to snipe lowest card on the Market window

### ISSUE THREAD

**Issue by Luffy-Ace** [ckalgos/fut-trade-enhancer#81]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Add feature switch on `transfert market windows` that allow user to snipe lowest card manually without need to use Autobuyer windows and setup the bot.
<img width="1524" alt="Capture d’écran 2022-09-27 à 16 05 37" src="https://user-images.githubusercontent.com/114497312/192548963-3ee43ed2-350c-467c-b482-c736131e3de3.png">

### Describe the Use Case

- When I select the transfert windows the switch appear in `OFF` state
- User can change the state to `ON`
- User launch a search 
- On Search result screen If the Switch was `ON` then automatically buy the lowest card.

### Additional Information

To avoid accidental buy I recommande : 

- The feature switch must be always off as initial state  
- Each time user change the windows (for example he select club or autobuyer windows, etc) the feature will be set to initial state `OFF` again.
- The switch work only if there's less the one page or less the 10 items.

**Comment by ckalgos** [comment]
Added in Latest Release
