### ISSUE TITLE
feat: add futbin price to position modifier 

### ISSUE THREAD

**Issue by justingoertz** [ckalgos/fut-trade-enhancer#83]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

The new position modifier card should also have the futbin price.(https://www.futbin.com/consumables/Position%20Change).

### Describe the Use Case

Same use case as the already implemented futbin prices for chem styles.

**Comment by ckalgos** [comment]
Added in Latest Release
