### ISSUE TITLE
bug: Non-player duplicates in auto pack opener

### ISSUE THREAD

**Issue by AndreiCnst30** [ckalgos/fut-trade-enhancer#84]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.3.4

### Platform

Webapp

### Current Behavior

When using the 'open pack automatically' feature with the following settings, non-player duplicate items go to transfer list aswell.

![image](https://user-images.githubusercontent.com/25981432/193402168-9de221e2-e652-4cbf-a857-3a7df14c4579.png)

### Expected Behavior

non-player duplicates should be quick sold

### Steps to Reproduce

go to store with settings (move to transfer list, quick sell, move to transfer list) and auto buy bronze packs until you get a duplicate non-player item. it will not be sold and you will find it in transfer list

**Comment by ckalgos** [comment]
This is the expected behaviour, all duplicates irrespective of players or consumables will be moved to transferlist. 

Only consumables of type Club Items can cause this issue, its better to handle them manually from transferlist
