### ISSUE TITLE
"Calculate Min Bin" should show the lowest price, not the average price.

### ISSUE THREAD

**Issue by cnbrkc** [ckalgos/fut-trade-enhancer#88]
I have another suggestion that I think is very important and beautiful.

When the "Calculate Min Bin" button is pressed, the data is scanned and the average of the lowest price in a certain quantity is shown to us as a result.

There is a problem here.

Because "minimum bin" means the lowest price. But it gives us an average price. We can see the avarage price already with futbin price. What we are looking for is the lowest price at the moment. Therefore, in this calculation, it should show us what the lowest price is at that moment. 

Or we should be given a choice as to how many lowest prices we want to see averaged over.

Or with a small add-on, it can show us the lowest 3-4 prices separately.

Please CK.

Let " Calculate Min Bin " show the lowest price which is the actual function (not the average). And let's sell at that price. In old versions, this price was automatically displayed when we clicked the Transfer List button.

Thank you very much for these good services. We love you.

**Comment by cnbrkc** [comment]
And I even have a more utopian idea :) I came up with the idea of a feature that can be useful for everyone, especially automating the work of those who open many packages or who buy coins with methods such as BPM and SPM. By adding the "Sell Min Bin" option next to the List Futbin Price option, the bot can find the lowest price for each card from the market and automatically list the transfer list one unit below it, so that it will not be banned :) Just like List Futbin.

You are amazing CK and I am sure that you will do the most correct and logical actions for us in the matters I have mentioned.

**Comment by ckalgos** [comment]
Added in the latest version
