### ISSUE TITLE
feat: List for FUTBIN in Auto Pack Opening

### ISSUE THREAD

**Issue by Kromat1x** [ckalgos/fut-trade-enhancer#90]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

On player items, on opening pack, have the option to list for Futbin price, besides the already available 3 options (quick sell, club, transfer list). For duplicates and non-player items I belive it's not needed. 

### Describe the Use Case

This is useful in the following case:
If I open a lot of packs (let's assume BPM) and send the players to transfer list, if I have any investments in the transfer list that I want to keep, I cannot use list futbin for the entire list, therefore, it would be useful to list pack players as I open the packs. This is just an idea, not mandatory, thanks a lot for everything. Love.

**Comment by ckalgos** [comment]
Added in latest release

**Comment by Kromat1x** [comment]
That's amazing. Thanks a lot. What does it do whenever it cannot find the price on futbin for one player? If it leaves in unassigned it won't be able to continue opening packs, right? I haven't encountered this, but it just crossed my mind.
