### ISSUE TITLE
feat: Ability to purchase players for FUTBIN/FUTWIZ from squad screen

### ISSUE THREAD

**Issue by captain-cronch** [ckalgos/fut-trade-enhancer#94]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Have the feature to purchase missing players in SBC solutions available on the squad screen.

### Describe the Use Case

For various objectives, I build a squad using concept players tailored to the given objective and would like to be able to quickly buy missing players.

### Describe Preferred Solution

Take the existing code that allows for missing players to be purchased for SBC solutions and make the same feature available on squad screens.

**Comment by ckalgos** [comment]
Added in the latest release
