### ISSUE TITLE
Potential Profit/Loss based on "bought price" and Futbin price

### ISSUE THREAD

**Issue by Jameskine** [ckalgos/fut-trade-enhancer#96]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/ckalgos/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Add potential Profit/Loss % based on "Bought Price" and Futbin price when clicking on a card and in transfer list.
Mockup: https://i.imgur.com/mWZj3TF.jpeg

### Describe the Use Case

Could be very interesting, in order to get better experience with the Script, to get the possibility to see beside the "Bought price" when clicking on a card, the real time Futbin price and the related % calculated of difference. (mockup I prepared for you: https://i.imgur.com/mWZj3TF.jpeg)

Could also be very useful to see the same values (bought price and futbin price with related % profit/loss) in the "Available items" not listed yet.
This feature could be interesting in order to "invest" and hold some cards and see at first view if that card is on potential profit or potential loss. (https://i.imgur.com/mWZj3TF.jpeg)

**Comment by ckalgos** [comment]
Added In Latest Release
